using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DogiWiki2.Models
{
    public class IndexModel
    {
        public string Filter { get; set; }

        public string SortBy { get; set; }

        public static List<String> SortByList = new List<string>
        {
            "Newest",
            "Random"
        };

        public static List<String> FilterList = new List<string>
        {
            "All",
            "Mix",
            "Affenpinscher",
            "Afghan Hound",
            "Airedale Terrier",
            "Akita",
            "Alaskan Malamute",
            "American English Coonhound",
            "American Eskimo Dog",
            "American Foxhound",
            "American Hairless Terrier",
            "American Staffordshire Terrier",
            "Anatolian Shepherd Dog",
            "Australian Cattle Dog",
            "Australian Shepherd",
            "Australian Terrier",
            "Basenji",
            "Basset Hound",
            "Beagle",
            "Bearded Collie",
            "Beauceron",
            "Bedlington Terrier",
            "Belgian Malinois",
            "Belgian Sheepdog",
            "Belgian Tervuren",
            "Bergamasco Sheepdog",
            "Berger Picard",
            "Bernese Mountain",
            "Bichons Frise",
            "Black Russian Terrier",
            "Black and Tan Coonhound",
            "Bloodhound",
            "Bluetick Coonhound",
            "Boerboel",
            "Border Collie",
            "Border Terrier",
            "Borzois",
            "Boston Terrier",
            "Bouviers des Flandre",
            "Boxer",
            "Briards",
            "Brittany",
            "Brussels Griffon",
            "Bull Terrier",
            "Bulldog",
            "Bullmastiff",
            "Cairn Terrier",
            "Canaan Dog",
            "Cane Corso",
            "Cardigan Welsh Corgi",
            "Cavalier King Charles Spaniel",
            "Cesky Terrier",
            "Chihuahua",
            "Chinese Crested",
            "Chinese Shar-Pei",
            "Chinook",
            "Chow Chow",
            "Cirneco dell’Etna",
            "Collie",
            "Coton de Tulear",
            "Dachshund",
            "Dalmatian",
            "Dandie Dinmont Terrier",
            "Doberman Pinscher",
            "Dogues de Bordeaux",
            "English Foxhound",
            "English Toy Spaniel",
            "Entlebucher Mountain Dog",
            "Finnish Lapphund",
            "Finnish Spitz",
            "Fox Terrier (Smooth)",
            "Fox Terrier (Wire)",
            "French Bulldog",
            "German Pinscher",
            "German Shepherd",
            "Giant Schnauzer",
            "Glen of Imaal Terrier",
            "Great Dane",
            "Great Pyrenee",
            "Greater Swiss Mountain Dog",
            "Greyhound",
            "Harrier",
            "Havanese",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Irish Terrier",
            "Irish Wolfhound",
            "Italian Greyhound",
            "Japanese Chin",
            "Keeshonden",
            "Kerry Blue Terrier",
            "Komondorok",
            "Kuvaszok",
            "Lagotti Romagnoli",
            "Lakeland Terrier",
            "Leonberger",
            "Lhasa Apso",
            "Lowchen",
            "Maltese",
            "Manchester Terrier",
            "Mastiff",
            "Miniature American Shepherd",
            "Miniature Bull Terrier",
            "Miniature Pinscher",
            "Miniature Schnauzer",
            "Neapolitan Mastiff",
            "Newfoundland",
            "Norfolk Terrier",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Lundehund",
            "Norwich Terrier",
            "Old English Sheepdog",
            "Otterhound",
            "Papillon",
            "Parson Russell Terrier",
            "Pekingese",
            "Pembroke Welsh Corgi",
            "Petits Bassets Griffons Vendeen",
            "Pharaoh Hound",
            "Plott",
            "Pointer",
            "Pointer (German Shorthaired)",
            "Pointer (German Wirehaired)",
            "Polish Lowland Sheepdog",
            "Pomeranian",
            "Poodle",
            "Portuguese Podengo Pequeno",
            "Portuguese Water Dog",
            "Pug",
            "Puli",
            "Pumi",
            "Pyrenean Shepherd",
            "Rat Terrier",
            "Redbone Coonhound",
            "Retriever (Chesapeake Bay)",
            "Retriever (Curly-Coated)",
            "Retriever (Flat-Coated)",
            "Retriever (Golden)",
            "Retriever (Labrador)",
            "Retriever (Nova Scotia Duck Tolling)",
            "Rhodesian Ridgeback",
            "Rottweiler",
            "Russell Terrier",
            "Saluki",
            "Samoyed",
            "Schipperke",
            "Scottish Deerhound",
            "Scottish Terrier",
            "Sealyham Terrier",
            "Setter",
            "Setter (English)",
            "Setter (Irish Red or White)",
            "Setter (Irish)",
            "Shetland Sheepdog",
            "Shiba Inu",
            "Shih Tzu",
            "Siberian Husky",
            "Silky Terrier",
            "Skye Terrier",
            "Sloughi",
            "Soft Coated Wheaten Terrier",
            "Spaniel (American Water)",
            "Spaniel (Boykin)",
            "Spaniel (Clumber)",
            "Spaniel (Cocker)",
            "Spaniel (English Cocker)",
            "Spaniel (English Springer)",
            "Spaniel (Field)",
            "Spaniel (Irish Water)",
            "Spaniel (Sussex)",
            "Spaniel (Welsh Springer)",
            "Spanish Water Dog",
            "Spinoni Italiani",
            "St. Bernard",
            "Staffordshire Bull Terrier",
            "Standard Schnauzer",
            "Swedish Vallhund",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Toy Fox Terrier",
            "Treeing Walker Coonhound",
            "Vizsla",
            "Weimaraner",
            "Welsh Terrier",
            "West Highland White Terrier",
            "Whippet",
            "Wirehaired Pointing Griffon",
            "Wirehaired Vizsla",
            "Xoloitzcuintli",
            "Yorkshire Terrier"
        };
    }
}