using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DogiWiki2.Models
{
    public class IndexModel
    {
        public string Filter { get; set; }

        public string SortBy { get; set; }

        public static List<String> SortByList = new List<string>
        {
            "Newest",
            "Random"
        };

        public static List<String> FilterList = new List<string>
        {
            "All",
            "Mix",
            "Affenpinscher",
            "Afghan Hound",
            "Akita",
            "Alaskan Malamute",
            "American Eskimo Dog",
            "American Foxhound",
            "Anatolian Shepherd Dog",
            "Australian Cattle Dog",
            "Australian Shepherd",
            "Basenji",
            "Basset Hound",
            "Beagle",
            "Bearded Collie",
            "Beauceron",
            "Belgian Malinois",
            "Belgian Tervuren",
            "Berger Picard",
            "Bernese Mountain",
            "Bichons Frise",
            "Bloodhound",
            "Boerboel",
            "Border Collie",
            "Borzois",
            "Bouviers des Flandre",
            "Boxer",
            "Briards",
            "Brittany",
            "Brussels Griffon",
            "Bulldog",
            "Bullmastiff",
            "Canaan Dog",
            "Cane Corso",
            "Chihuahua",
            "Chinese Crested",
            "Chinese Shar-Pei",
            "Chinook",
            "Chow Chow",
            "Cirneco dell’Etna",
            "Collie",
            "Coonhound",
            "Corgi",
            "Coton de Tulear",
            "Dachshund",
            "Dalmatian",
            "Doberman Pinscher",
            "Dogues de Bordeaux",
            "Double Doodle",
            "English Foxhound",
            "Entlebucher Mountain Dog",
            "Finnish Lapphund",
            "Finnish Spitz",
            "French Bulldog",
            "German Pinscher",
            "German Shepherd",
            "Giant Schnauzer",
            "Goldendoodle",
            "Golden Retriever",
            "Great Dane",
            "Great Pyrenee",
            "Greater Swiss Mountain Dog",
            "Greyhound",
            "Harrier",
            "Havanese",
            "Ibizan Hound",
            "Irish Wolfhound",
            "Italian Greyhound",
            "Japanese Chin",
            "Keeshonden",
            "Komondorok",
            "Kooikerhondje",
            "Kuvaszok",
            "Labrador",
            "Labradoodle",
            "Lagotti Romagnoli",
            "Leonberger",
            "Lhasa Apso",
            "Lowchen",
            "Maltese",
            "Mastiff",
            "Miniature American Shepherd",
            "Miniature Pinscher",
            "Miniature Schnauzer",
            "Neapolitan Mastiff",
            "Newfoundland",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Lundehund",
            "Otterhound",
            "Papillon",
            "Pekingese",
            "Petits Bassets Griffons Vendeen",
            "Pharaoh Hound",
            "Plott",
            "Pointer",
            "Pomeranian",
            "Poodle",
            "Portuguese Podengo Pequeno",
            "Portuguese Water Dog",
            "Pug",
            "Puli",
            "Pumi",
            "Pyrenean Shepherd",
            "Retriever (Chesapeake Bay)",
            "Retriever (Nova Scotia Duck Tolling)",
            "Rhodesian Ridgeback",
            "Rottweiler",
            "Saluki",
            "Samoyed",
            "Schipperke",
            "Scottish Deerhound",
            "Setter",
            "Sheepdog",
            "Shiba Inu",
            "Shih Tzu",
            "Siberian Husky",
            "Sloughi",
            "Spaniel",
            "Spanish Water Dog",
            "Spinoni Italiani",
            "St. Bernard",
            "Standard Schnauzer",
            "Swedish Vallhund",
            "Terrier",
            "Tibetan Mastiff",
            "Vizsla",
            "Weimaraner",
            "Whippet",
            "Wirehaired Pointing Griffon",
            "Wirehaired Vizsla",
            "Xoloitzcuintli",
        };
    }
}